spring:
  security:
    user:
      name: berry
      password: pwd123

server:
  port: 8761
  undertow:
    buffer-size: 1024
    direct-buffers: true
    io-threads: 4
    worker-threads: 20

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

  server:
    waitTimeInMsWhenSyncEmpty: 0